build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related prod APIs "
  contactDetails:
    name: "Deepak Kokate - Developer"
    email: "deeps@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345