spring:
  application:
    name: configserver
  profiles:
    active: git
  cloud:
    config:
      server:
        enabled: true
        #native:
         # search-locations: classpath:/config
           #search-locations: file:///C://Users//91767//Documents//config
        git:
          uri: https://github.com/rashPatil1/eazybytes-config.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"


server:
  port: 8071


management:
  endpoints:
    web:
      exposure:
        include: "*"