build:
    version: "2.0"

accounts:
    message: "Welcome to EazyBank accounts related QA APIs "
    contactDetails:
        name: "Smitha Roy - QA lead"
        email: "smitha@eazybank.com"
    onCallSupport:
        - (666) 555-1234
        - (666) 523-1345

